// Este archivo solo contiene los datos de productos
export const productos = [
  {
    id: 1,
    nombre: "Silla ergonómica",
    descripcion: "Silla con soporte lumbar y ajuste de altura.",
    precio: 320,
    imagen: "https://via.placeholder.com/200x150?text=Silla",
  },
  {
    id: 2,
    nombre: "Escritorio de madera",
    descripcion: "Amplio escritorio de roble con cajones.",
    precio: 560,
    imagen: "https://via.placeholder.com/200x150?text=Escritorio",
  },
  {
    id: 3,
    nombre: "Lámpara LED",
    descripcion: "Lámpara de escritorio con luz regulable.",
    precio: 120,
    imagen: "https://via.placeholder.com/200x150?text=Lampara",
  },
  {
    id: 4,
    nombre: "Archivador metálico",
    descripcion: "Archivador de 3 cajones para oficina.",
    precio: 250,
    imagen: "https://via.placeholder.com/200x150?text=Archivador",
  },
  {
    id: 5,
    nombre: "Monitor 24 pulgadas",
    descripcion: "Pantalla Full HD ideal para oficina y gaming.",
    precio: 800,
    imagen: "https://via.placeholder.com/200x150?text=Monitor",
  },
  {
    id: 6,
    nombre: "Teclado mecánico",
    descripcion: "Teclado mecánico retroiluminado con switches azules.",
    precio: 180,
    imagen: "https://via.placeholder.com/200x150?text=Teclado",
  },
  {
    id: 7,
    nombre: "Mouse inalámbrico",
    descripcion: "Mouse ergonómico con conexión Bluetooth.",
    precio: 90,
    imagen: "https://via.placeholder.com/200x150?text=Mouse",
  },
  {
    id: 8,
    nombre: "Impresora multifuncional",
    descripcion: "Imprime, copia y escanea con conectividad WiFi.",
    precio: 950,
    imagen: "https://via.placeholder.com/200x150?text=Impresora",
  },
  {
    id: 9,
    nombre: "Pizarra acrílica",
    descripcion: "Pizarra blanca magnética de 120x90 cm.",
    precio: 400,
    imagen: "https://via.placeholder.com/200x150?text=Pizarra",
  },
  {
    id: 10,
    nombre: "Organizador de escritorio",
    descripcion: "Mantén tus útiles ordenados con este organizador compacto.",
    precio: 75,
    imagen: "https://via.placeholder.com/200x150?text=Organizador",
  },
  {
    id: 11,
    nombre: "Auriculares con micrófono",
    descripcion: "Headset cómodo para videollamadas y música.",
    precio: 210,
    imagen: "https://via.placeholder.com/200x150?text=Auriculares",
  },
  {
    id: 12,
    nombre: "Sofá de oficina",
    descripcion: "Sofá de cuero sintético para sala de espera.",
    precio: 1500,
    imagen: "https://via.placeholder.com/200x150?text=Sofa",
  },
]
